### ISSUE TITLE
Incorrect width in some buffers (NERDTree, signcolumn?)

### ISSUE THREAD

**Issue by sergei-mironov** [sergei-grechanik/vim-terminal-images#2]
All images seem to be 1 column wider than required if NERDTree is used. Another suspect is `signcolumn`. This hack seems to work https://github.com/grwlf/vim-terminal-images/blob/18842f15608046124366e3c3484837626b41fcd9/autoload/terminal_images.vim#L224

**Comment by sergei-grechanik** [comment]
It's the sign column. Looks like the method I use to detect whether the sign column is present is wrong or outdated.

**Comment by sergei-grechanik** [comment]
Please check if the latest master fixes the issue

**Comment by sergei-mironov** [comment]
Looks fine now, thanks!
